# Generated by Django 5.1.3 on 2025-08-18 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "sell_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=18,
                        null=True,
                        verbose_name="قیمت فروش",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("formal", "لباس مجلسی"),
                            ("sport", "لباس اسپرت"),
                            ("shoes", "کفش"),
                            ("bag", "کیف"),
                            ("accessory", "اکسسوری"),
                            ("swim", "مایو"),
                            ("underwear", "لباس زیر"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="گروه کالا",
                    ),
                ),
            ],
            options={
                "verbose_name": "کالا",
                "verbose_name_plural": "کالاها",
            },
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[("customer", "مشتری"), ("vendor", "فروشنده")],
                        default="customer",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "طرف حساب",
                "verbose_name_plural": "طرف حساب\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qty",
                    models.DecimalField(decimal_places=0, default=0, max_digits=18),
                ),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="ledger.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_miladi", models.DateField()),
                (
                    "op_type",
                    models.CharField(
                        choices=[
                            ("خرید", "خرید"),
                            ("فروش", "فروش"),
                            ("دریافت", "دریافت"),
                            ("پرداخت", "پرداخت"),
                            ("استفاده خودم", "استفاده خودم"),
                        ],
                        max_length=20,
                        verbose_name="نوع عملیات",
                    ),
                ),
                ("qty", models.DecimalField(decimal_places=0, max_digits=18)),
                ("unit_price", models.DecimalField(decimal_places=0, max_digits=18)),
                ("total_price", models.DecimalField(decimal_places=0, max_digits=18)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="ledger.item",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="ledger.party",
                    ),
                ),
                ("date_shamsi", models.CharField(default=0, max_length=10)),
                (
                    "invoice_no",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="شماره فاکتور",
                    ),
                ),
                (
                    "settlement_method",
                    models.CharField(
                        choices=[
                            ("کارت خوان 1", "کارت خوان 1"),
                            ("کارت خوان 2", "کارت خوان 2"),
                            ("نقدی", "نقدی"),
                            ("حساب بلو", "حساب بلو"),
                            ("حساب 5802", "حساب 5802"),
                            ("حساب 1901", "حساب 1901"),
                        ],
                        default="کارت خوان 1",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "تراکنش",
                "verbose_name_plural": "تراکنش\u200cها",
            },
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["name"], name="ledger_item_name_1f8e6e_idx"),
        ),
        migrations.AddIndex(
            model_name="party",
            index=models.Index(fields=["name"], name="ledger_part_name_a560d6_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["date_miladi"], name="ledger_tran_date_mi_5c68d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["date_shamsi", "op_type"], name="ledger_tran_date_sh_701961_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["op_type"], name="ledger_tran_op_type_14e67f_idx"
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="avg_cost",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=18, verbose_name="میانگین موزون"
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="last_buy_cost",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=18,
                verbose_name="آخرین قیمت خرید",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="cogs",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=18,
                null=True,
                verbose_name="بهای تمام\u200cشده",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[],
            options={
                "verbose_name": "پرداخت",
                "verbose_name_plural": "پرداخت\u200cها",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("ledger.transaction",),
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[],
            options={
                "verbose_name": "دریافت",
                "verbose_name_plural": "دریافت\u200cها",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("ledger.transaction",),
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="ledger_tran_date_sh_701961_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="ledger_tran_op_type_14e67f_idx",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="cogs",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date_miladi",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date_shamsi",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="invoice_no",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ledger.item",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="op_type",
            field=models.CharField(
                choices=[
                    ("فروش", "فروش"),
                    ("خرید", "خرید"),
                    ("دریافت", "دریافت"),
                    ("پرداخت", "پرداخت"),
                    ("استفاده خودم", "استفاده خودم"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="party",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="ledger.party",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="qty",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="settlement_method",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="total_price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="unit_price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["party", "op_type"], name="ledger_tran_party_i_d31a8d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_price__gte", 0)),
                name="trx_total_price_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("op_type__in", ["فروش", "خرید", "استفاده خودم"]), _negated=True
                    ),
                    models.Q(
                        ("item__isnull", False), ("qty__gt", 0), ("unit_price__gte", 0)
                    ),
                    _connector="OR",
                ),
                name="trx_trade_requires_item_qty_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("op_type__in", ["دریافت", "پرداخت"]), _negated=True),
                    models.Q(
                        ("item__isnull", True),
                        ("qty__isnull", True),
                        ("unit_price__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="trx_money_moves_no_item_qty_price",
            ),
        ),
        migrations.RemoveField(
            model_name="party",
            name="role",
        ),
        migrations.AddField(
            model_name="party",
            name="is_customer",
            field=models.BooleanField(default=False, verbose_name="مشتری"),
        ),
        migrations.AddField(
            model_name="party",
            name="is_supplier",
            field=models.BooleanField(default=False, verbose_name="فروشنده"),
        ),
        migrations.AlterField(
            model_name="party",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name="party",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_customer", True), ("is_supplier", True), _connector="OR"
                ),
                name="party_at_least_one_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("op_type__in", ["دریافت", "پرداخت"]), _negated=True),
                    models.Q(
                        ("item__isnull", True),
                        ("qty__isnull", True),
                        ("unit_price__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="trx_money_moves_no_item_qty_price_v2",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="party",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="ledger.party",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="transaction",
            name="trx_trade_requires_item_qty_price",
        ),
        migrations.RemoveConstraint(
            model_name="transaction",
            name="trx_money_moves_no_item_qty_price_v2",
        ),
        migrations.RemoveConstraint(
            model_name="transaction",
            name="trx_total_price_non_negative",
        ),
        migrations.RemoveConstraint(
            model_name="transaction",
            name="trx_money_moves_no_item_qty_price",
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_price__gte", 0)),
                name="trx_total_price_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("op_type__in", ["دریافت", "پرداخت"]), _negated=True),
                    models.Q(
                        ("item__isnull", True),
                        ("qty__isnull", True),
                        ("unit_price__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="trx_money_moves_no_item_qty_price",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="transaction",
            name="trx_total_price_non_negative",
        ),
        migrations.RemoveConstraint(
            model_name="transaction",
            name="trx_money_moves_no_item_qty_price",
        ),
    ]
