# Generated by Django 5.1.3 on 2025-09-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="invoice_no",
        ),
        migrations.AddField(
            model_name="transaction",
            name="description",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="op_type",
            field=models.CharField(
                choices=[
                    ("SELL", "فروش"),
                    ("BUY", "خرید"),
                    ("RCV", "دریافت"),
                    ("PAY", "پرداخت"),
                    ("USE", "استفاده خودم"),
                ],
                max_length=15,
            ),
        ),
    ]
