# Generated by Django 5.1.3 on 2025-09-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0002_remove_transaction_invoice_no_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="settlement_method",
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("کارت خوان 1", "کارت خوان 1"),
                    ("کارت خوان 2", "کارت خوان 2"),
                    ("نقدی", "نقدی"),
                    ("حساب بلو", "حساب بلو"),
                    ("حساب 5802", "حساب 5802"),
                    ("حساب 1901", "حساب 1901"),
                ],
                default="نقدی",
                max_length=20,
                null=True,
            ),
        ),
    ]
