# Generated by Django 5.1.3 on 2025-09-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0003_remove_transaction_settlement_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("POS2", "کارت خوان جدید"),
                    ("ACC3", "حساب بلو"),
                    ("CASH", "نقدی"),
                    ("POS1", "کارت خوان قدیم"),
                    ("ACC2", "حساب 5802"),
                    ("ACC1", "حساب 1901"),
                    ("HEN1", "کارت هنگامه"),
                    ("HEN2", "حساب هستی"),
                ],
                default="POS2",
                max_length=10,
                null=True,
            ),
        ),
    ]
