# Generated by Django 5.1.3 on 2025-09-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0004_alter_transaction_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_cogs_temp",
            field=models.BooleanField(default=False),
        ),
    ]
