# Generated by Django 5.1.3 on 2025-09-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0005_transaction_is_cogs_temp"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="commission_amount",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="مبلغ ثابت فروشنده (برای هر واحد)"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="commission_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="درصد سهم فروشنده از فروش",
            ),
        ),
    ]
