# Generated by Django 5.1.3 on 2025-09-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0006_item_commission_amount_item_commission_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_consignment",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="item",
            name="commission_amount",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="commission_percent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("formal", "لباس مجلسی"),
                    ("sport", "لباس اسپرت"),
                    ("shoes", "کفش"),
                    ("bag", "کیف"),
                    ("accessory", "اکسسوری"),
                    ("swim", "مایو"),
                    ("underwear", "لباس زیر"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="sell_price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
