# Generated by Django 5.1.3 on 2025-09-16 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0007_item_is_consignment_alter_item_commission_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="avg_cost",
        ),
    ]
