# Generated by Django 5.1.3 on 2025-10-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0008_remove_inventory_avg_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="commission_open",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="op_type",
            field=models.CharField(
                choices=[
                    ("SELL", "فروش"),
                    ("BUY", "خرید"),
                    ("RCV", "دریافت"),
                    ("PAY", "پرداخت"),
                    ("USE", "استفاده/هدیه"),
                ],
                max_length=15,
            ),
        ),
    ]
