# Generated by Django 5.1.3 on 2025-10-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0009_item_commission_open_alter_transaction_op_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="commission_open",
        ),
    ]
