# Generated by Django 5.2.4 on 2025-10-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_remove_item_commission_open'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='party',
            name='party_at_least_one_role',
        ),
        migrations.AlterField(
            model_name='party',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='party',
            name='is_supplier',
            field=models.BooleanField(default=False),
        ),
    ]
